name: firebase_analytics_web
publish_to: none
description: The web implementation of firebase_analytics
version: 0.5.5+22

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.23
  firebase_analytics_platform_interface:
    path: ../firebase_analytics_platform_interface
  firebase_core: ^2.25.5
  firebase_core_web: ^2.11.5
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAnalyticsWeb
        fileName: firebase_analytics_web.dart
